### ISSUE TITLE
New function: add_block

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/Project-Allium#107]
**Objective:**
Now that the `blockchain` class is ready, we can start doing some file i/o. All blocks need to be appended to the blockchain, so there will be a function to support this.

**TODO:**
In `blockchain.py`, write a _class_ function called `add_block`, which takes in a mined `block` as a parameter. 

1. First, get the `size` of the `block` using the function from [issue #123](https://github.com/SIGBlockchain/Project-Allium/issues/123).
2. Next, get the `magic_bytes` sequence delimiter, which is 3652501241 in byte form. Note: This can be declared as a global at the top of the file so we only need to convert it once.
3. After that, concatenate `magic_bytes` + `size` + `block` to form a `payload`.
4. Finally, open the `blockfile` in binary append mode, and write the payload to the file.

**Testing:**
Several test functions should be made. One can test what happens if you mine a single block and add it to the chain. Check to see that that block is inside the file. For another function, mine 3-4 blocks, and check that the contents of the file is the concatenation of these blocks. This assures us that we are appending and not overwriting. We will create an extraction function for specific blocks in another issue.

**Comment by JoshuaRM** [comment]
Hello, I am interested in working on this. I have read through issues #105 and #112 as well and would be interested in working on these consecutively. I will begin working on this issue shortly

**Comment by kstola2** [comment]
@JoshuaRM I have sent you an invite.

**Comment by JoshuaRM** [comment]
Regarding step 3 in the TODO; do you want the payload to be a concatenation of magic_bytes (in byte form), size (also byte form), and the block itself, or the data within the block?

**Comment by jldistefano** [comment]
You are going to want to only use function specified under line 193, the one that says..
############################################################################
############################ NEW CODE BELOW HERE ###########################
############################################################################
To create a block use .mine(), which will output a 74 byte string

**Comment by jldistefano** [comment]
The code before line 193 was for demonstration and educational purposes, it is no longer used in new functions.

**Comment by kstola2** [comment]
Anything above the line is deprecated and I will make an issue to clean up the `block.py` and `block.test.py` files to remove all deprecated code.

**Comment by JoshuaRM** [comment]
Another problem I am having is with writing to the file, more specifically in the `blockchain.test.py` 
The problem seems to be the test_constructor method running AFTER the other tests, causing it to overwrite the file. To confirm this I changed the write method to binary append instead of binary write (to test this theory) and it does appear that the test_constructor runs after and overwrites the file.

**Comment by kstola2** [comment]
Tests in `unittest` objects get run in alphabetical order, so that's probably why the constructor runs after. This shouldn't be a problem though, because we made the scope of each test restricted to their corresponding test functions. 

Another thing is that the `setUp` and `tearDown` functions get called (respectively) before and after  each test function. This means that before each test, the a new `blockfile` is generated and after each test the `blockfile` is wiped out from the directory. This way, each test is "minding its own business" so to speak, and does not interact with other tests. TLDR; the `test_constructor` is working as intended.

**Comment by JoshuaRM** [comment]
I was not aware of the alphabetical order so thank you for that. I thought to use the same file was the idea, however if I saved the payload to its own file this problem would be resolved. Is there a preferred name for the payload saves file?

**Comment by kstola2** [comment]
You should be able to save it to the blockfile generated in the blockchain class. It's generated whenever `setUp` is called.

**Comment by JoshuaRM** [comment]
The issue is the `testfile` because it is generated in setUp, and used by both the test_constructor, and the test_add_block methods and the latter appends to the file. This was the filename I was referring to changing. Saving it into blockfile, but not named `testfile`. I was thinking to create a Blockchain object in the test_add_block method, with a different filename such as `add_block_testfile` for example.

**Comment by jldistefano** [comment]
Could you push your changes to a branch so we can help you debug your code?

**Comment by jldistefano** [comment]
Or just paste the code in here using the code button over here ---------vv

**Comment by kstola2** [comment]
I think you should push your code so we can see it. But the whole point of doing setup and teardown is so that we dont need to generate a new blockchain object each time you run a test.

**Comment by JoshuaRM** [comment]
I managed to solve it last night, didn't fully understand the importance of the tearDown() method, but re enabling it solved my problem. I created a pull request with add_block, and get_size_bytes. Thanks for your help!

**Comment by kstola2** [comment]
Credit to @JoshuaRM for contributing to this issue's completion.
