### ISSUE TITLE
New file: blockchain metadata

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/Project-Allium#151]
**Objective:**
To address blockchain search efficiency, our group decided to create a metadata file that stored a list of locations in the blockchain file. 

**TODO:**
In `blockchain.py`, add an additional parameter to the constructor called `metadata`.  If the file does not exist, create the file.

**Testing:**
Add on to the `blockchain constructor test`. Make sure to also update `setUp` and `tearDown` to include this file. NOTE: the `metadata` file will be using `json` formatting so make sure it is has the `.json` extension.

**Comment by JoshuaRM** [comment]
I would like to work on this issue.

**Comment by kstola2** [comment]
@JoshuaRM You don't need to comment to assign yourself - just click on the gear by assignees and select your name.
