### ISSUE TITLE
New feature: metadata

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/Project-Allium#152]
**Objective:**
Each time we add a block, we should keep track of the number of blocks we have and the last block we added.

**TODO:** (`blockchain.py`)

- In the blockchain constructor:
1. Initialize a dictionary object called `self.metadata`.
2. Create a key called `block_count` that is initialized to `0`.
3. Create a key called `last_block` that is initialized to an empty byte string.
4. Create a key called `block_indexes` that is initialized to `[]`.

- In `add_block`:
1. Get the `index` in the file at which you're about to store `block` **before it is stored**. This should be just the size of the file minus one, since the file is one long byte string, but testing will show if this is true.
Append `index` to the `block_indexes` list.
2. After the `block` is stored, update the `last_block` to be equal to it.
3. In the `add_block` function, increment the `block_count` by `1`.

**Testing:**
Test the constructor to see it is initializing the metadata dictionary properly.
Call `add_block` and check to make sure the block that is stored in `self.metadata`.

**Comment by JoshuaRM** [comment]
I would like to work on this

**Comment by kstola2** [comment]
@JoshuaRM  Since this is called in `add_block`, testing should involve calling that function and checking to make sure the correct information is being stored in the metadata of the object.
