### ISSUE TITLE
New function: get_peer_tracker

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/Project-Allium#186]
**Objective:**
To accommodate peer discovery, we will be using the ACM provided peer tracker as a "meeting location" for peers who want to connect to the Allium network. The actual links are not provided in this issue because they have the potential to be abused. So if someone wants to work on **networks** and use the peer tracker they will need the links disclosed to them privately. This is so that we can keep track of everyone who has the links during the development process and prevent potential misuse/overuse of the server.

**TODO:**
- Create a function called `get_peer_tracker` that takes as a parameter `tracker_links`. 
- With `tracker_links` open, `json.load` the contents and return it.

**Testing:**
- The dictionary should tentatively have 3 keys, which are `add`, `get`, and `clear`. You will need to create a a test file with a `.json` extension for the test with these keys. Make sure your test deletes the file upon completion.

**Comment by kstola2** [comment]
Closed until issue progression gets figurd out.

**Comment by kstola2** [comment]
Reopened

**Comment by bashbashbash** [comment]
Completed
