### ISSUE TITLE
New functions for transactions

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/Project-Allium#187]
**Objective:**
One issue I've encountered in creating new transaction issues is the result of overlooking the fact that transactions can have multiple inputs and outputs. This issue will have a bunch of functions that should encapsulate the whole transaction process properly. I'll write it in steps even if the functions already exist so that the process is clearly understood.

**NOTE:**
They don't need to be all completed at once. If anyone wants to just do a one at a time I can mark them off here as **DONE** as PR's get approved.

**Steps:**
1. `create_output`  **DONE**
- takes in a `value` and `recipient` 
- converts `value` to long in byte form 
- concatenates parameters in order
- returns result.
2. `cat_input_fields` **DONE**
- takes in a `prev_tx_hash`, `output_index`, and `prev_recipient` 
- converts `output_index` to short in byte form and concatenates parameters in order 
- return result. 
3. `cat_tx_fields` **DONE**
- takes in a `version`, a list of `inputs`, and a list of `outputs` 
- convert the `version` to integer byte form
- get the `num_inputs` and `num_outputs` from the `len` of the inputs` and `outputs` respectively 
- convert these to shorts in byte form 
- concatenate the parameters in the following order: 
version number + # inputs + input _0_...input _n_ + # outputs + output _0_... output _n_ 
- return result 
4. `sign_transaction` **DONE**
- modify existing function parameters to be `unsigned_tx` and a `private_key`. 
- Steps 3-6 from #150  should remain the same. 
5. `create_tx` **DONE**
- takes in a `version`, a list of `unsigned_inputs`, a list of `outputs`, and `private_key`
- get the `unsigned_tx` by passing all the parameters except `private_key` to `cat_tx_fields`
- get the `signature` by passing `unsigned_tx` and `private_key` to `sign_transaction`
- generate the `public_key`
- for each `input` in `unsigned_inputs`, replace the `prev_recipient` portion of the input with: 
(`signature` + `public_key`)
- Now each each unsigned input is signed.
- call `cat_tx_fields` once more with the signed inputs this time.
- return result

**Testing:**
For testing you should:
- generate a private key first. 
- create an empty list for outputs and inputs.
- fill each list; preferably one test function can have a singleton list and another one can have some arbitrary size. use `create_output` and `cat_input_fields` to generate elements.
- pass version `1`, along with your inputs and outputs to `create_tx`. 
- Check to see if the appropriate fields are in the correct spots.

**Comment by jldistefano** [comment]
I was working on this issue and was having trouble developing tests, especially for `create_tx` how exactly would I go about creating an unsigned input, as `create_input` takes a signature?

**Comment by kstola2** [comment]
`create_input` is not a part of this issue. Also note `cat_input_fields` was originally not marked as **DONE** but now it is.

**Comment by kstola2** [comment]
I should specify, that the past transaction functions weren't coming together as intended and this issue is meant to replace all of them (with the exception of the merkle function).

**Comment by kstola2** [comment]
I went ahead and added Deprecation warnings to old input related functions so please update from dev.

**Comment by kstola2** [comment]
I don't think so. Is that happening?

**Comment by jldistefano** [comment]
So in testing `create_tx`, I cant really confirm the signature field as I cannot generate an identical one in the test function. Is it okay to skip that step then, or is there a way I can check if the key is valid in that test.

**Comment by kstola2** [comment]
I think the best option would be to just test it the same way as `test_sign_transaction`

**Comment by kstola2** [comment]
Completed
