### ISSUE TITLE
GUI: Create New UI File and Initialize Window Size

### ISSUE THREAD

**Issue by jldistefano** [SIGBlockchain/Project-Allium#191]
**Objective:**
We will be creating a new UI file seperate from the old one. So in this file we need to write the include statements so we are able to work with pyqt5. In addition to this we should initialize the window size and title.
**To Do:**
- Create a file in user_interface called GUI.py.
- Write the include statements necessary for using pyqt5
- Create a class Gui(QMainWindow) that contains all members and functions related to the UI
- Create a function `__init__(self):` This will set the title, its starting location, and its size
- Create a function called `initUI(self):` This will apply the title to the window, and set the size as fixed. This function should also set 2 fonts, bigFont and normalFont. See old ui.py 
- Add the main function to execute the GUI and load it, see the `if __name__ == '__main__:` block in ui.py
For now set the title to Allium Wallet [version], and the size to 1000x400. Both of these will likely change in the future.

**Useful Resources:**
Most of these elements can be copied over from ui.py, though the include statements should only include what we are currently using.
PyQt5 is a python implementation of Qt in C++, so most of the good documentation will be in C++. However beyond syntax, it is identical to PyQt5. Any documentation I link to will be in C++.
[QMainWindow Documentation](http://doc.qt.io/qt-5/qmainwindow.html)
This will be the object that represents the main window for the GUI. It will often be referred to using `self` as that is how it is implemented in the class definition.
[setFixedSize Documentation](http://doc.qt.io/qt-5/qwidget.html#setFixedSize-1)
Objects in PyQt5 often inherit elements from many other objects. QMainWindow inherits elements from QWidget, allowing this function to be called on it. This will prevent resizing of the window which is what we want.
![gui v1](https://user-images.githubusercontent.com/43453042/49477139-94be4580-f7e1-11e8-8a74-ce375bd838ec.png)

**Comment by Vineet77** [comment]
I think it would be better to call the file GUI.py rather than new_ui.py, a better name in my opinion.

**Comment by jldistefano** [comment]
You're not wrong, that would likely be a better name

**Comment by Vineet77** [comment]
I created the new file and did a pull request

**Comment by kstola2** [comment]
Completed
