### ISSUE TITLE
Fix Long Bytes on Unix Systems

### ISSUE THREAD

**Issue by jldistefano** [SIGBlockchain/Project-Allium#219]
**Objective:**
Apparently Long Integers have different sizes on different platforms, [see here.](https://software.intel.com/en-us/articles/size-of-long-integer-type-on-different-architecture-and-os)

**To Do:**
To Fix this we are going to change anything using long integers to use long long integers.
This is done by replacing any 'L' in a pack/unpack statement with a 'Q'
Any function that decodes long bytes must now read 8 bytes instead of 4

**Comment by kstola2** [comment]
Completed
